### ISSUE TITLE
Submit to MELPA?

### ISSUE THREAD

**Issue by swsnr** [andrmuel/projectile-git-autofetch#2]
I'd love to use this package through MELPA.  Would you mind if I submitted it?

**Comment by andrmuel** [comment]
I agree, it would be nice to have it in MELPA. Feel free to submit...

**Comment by swsnr** [comment]
@andrmuel Thanks; see https://github.com/melpa/melpa/pull/4396

Would you mind to push a "0.1.0" tag to make the package appear on MELPA Stable as well?

**Comment by andrmuel** [comment]
OK. Just added the tag.
