### ISSUE TITLE
Add an 'after successful fetch' hook?

### ISSUE THREAD

**Issue by danielcompton** [andrmuel/projectile-git-autofetch#5]
I would like to be able to refresh my Magit status buffer after this project finishes a fetch which returns new commits. Would a change to be able to add an after-hook be accepted? I'm pretty new to elisp, but this seems pretty simple.

**Comment by andrmuel** [comment]
If the default behaviour does not change (i.e. hooks empty by default), 
I don't see any problem. I currently have no access to my personal PC, 
so it will probably take 1-2 weeks to merge though.

**Comment by danielcompton** [comment]
As I've thought about this more, it seems like it may be challenging to identify the right Magit status buffers to refresh, and refreshing all of them is probably not ideal. I'll investigate what's available and do some noodling. Thanks!

**Comment by david-come-pix4d** [comment]
What's the status on this ?

Because I would like to actually run a forge-pull after an auto-fetch,
I tried with an advice like this
```
(defun run-forge-pull (&optional ARG PRED)
  (message "Hello")
  (forge-pull)
  )
(advice-add 'run-forge-pull :after 'projectile-git-autofetch-run)
```
but it did not work.

**Comment by andrmuel** [comment]
This would run after all projects have been fetched, and I think the `default-directory` variable would be depending on what your current buffer is. I'm not using forge, but I assume you would have to be inside a specific project.

I assume you would want to run this for every project?
I could add a hook so you can configure your own function. Should this be executed for every project or just the ones that fetched something?

This should be quite simple, but I will likely not get to it before end of next week.

**Comment by david-come-pix4d** [comment]
Ideally, I would like an hook that runs for every project that's fetch with a way to know it's path/git folder.

**Comment by andrmuel** [comment]
I have added two hook variables in branch ` feature/after-fetch-hooks`. 

`projectile-git-autofetch-after-fetch-hook` runs for every fetched repository, independently of new content.

`projectile-git-autofetch-after-successful-fetch-hook` runs for every repository where new content was fetched.
Please let me know if this works for you.

**Comment by david-come-pix4d** [comment]
They are working just fine !

**Comment by andrmuel** [comment]
Great, thank you for the confirmation - merged to master now.
