### ISSUE TITLE
Use faster checking method for GitHub

### ISSUE THREAD

**Issue by danielcompton** [andrmuel/projectile-git-autofetch#6]
GitHub has an [API](https://developer.github.com/v3/repos/commits/#get-the-sha-1-of-a-commit-reference) which lets you [efficiently](https://developer.github.com/changes/2016-02-24-commit-reference-sha-api/) get the current SHA of a particular reference (branch, tag, e.t.c.). Heavy GitHub users are encouraged to use it, e.g. [Cocoapods](http://blog.cocoapods.org/Master-Spec-Repo-Rate-Limiting-Post-Mortem/), [Spacemacs](https://github.com/syl20bnr/spacemacs/issues/6692).

This is more efficient and faster than doing a full fetch (at least on GitHub's side).

Here is an example of what it looks like when you are not up-to-date:

```
$ http "https://api.github.com/repos/Homebrew/homebrew-core/commits/master" \
   "Accept: application/vnd.github.3.sha" \
   "If-None-Match: \"aaaaa3244ad4633d382cc57ab80614ea0c640839\""
HTTP/1.1 200 OK
...
ETag: "307ab3244ad4633d382cc57ab80614ea0c640839"
Content-Length: 40
...
307ab3244ad4633d382cc57ab80614ea0c640839
```

And here is what you get when you are up to date:

```
$ http "https://api.github.com/repos/Homebrew/homebrew-core/commits/master" \
   "Accept: application/vnd.github.3.sha" \
   "If-None-Match: \"307ab3244ad4633d382cc57ab80614ea0c640839\""
HTTP/1.1 304 Not Modified
...
ETag: "307ab3244ad4633d382cc57ab80614ea0c640839"
Status: 304 Not Modified
...
```

For public GitHub repositories this is fine to do unauthenticated, but for private ones, you would need an API key. Is this in the scope of this project, or does it make things too complicated?

**Comment by andrmuel** [comment]
It looks like this would be straightforward to implement; however the 
code would be specific to GitHub, and after all, the primary goal of the 
package is to actually fetch new commits.

I'm not strongly biased against this, but I don't see a significant 
benefit either, so I think for the moment I'd rather keep the code generic.
